config {
    type: "table",
    schema: "golf_warehouse",
    bigquery: {
        clusterBy: ["practice_date"]
    }
}

SELECT
  practice_date,
  club_duplicate,
  MIN(carry_yds) AS min_carry_yds,
  MAX(carry_yds) AS max_carry_yds,
  MAX(carry_yds) - MIN(carry_yds) AS dispersion_yds,
  AVG(carry_yds) AS avg_carry_yds_per_practice,
FROM
  ${ref("carry_yds_ex_outliers")}
GROUP BY
  ALL
